version: '3.8'

services:
  horoscopeapi:
    build:
      context: ./HoroscopePredictorAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__HoroscopeDBConnection: server=mydatabase;database=HoroscopeDB;User=SA;Password=Afeef@123;TrustServerCertificate=true
      JWT__Issuer: http://horoscopeapi
      JWT__Audience: http://horoscopeapi
    depends_on:
      - mydatabase
    

  horoscopeapp:
    build:
      context: ./HoroscopePredictorApp
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      HoroscopeAppConfiguration__BaseUrl: http://horoscopeapi
    depends_on:
      - horoscopeapi

  mydatabase:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Afeef@123
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
      MSSQL_DATABASE: localdb
    ports:
      - "1433:1433"
    volumes:
      - mydatabasedata:/var/opt/mssql
volumes:
   mydatabasedata:
   
